# general configuration parameters
port: 8080

# logging details
log: 
  file: log/tpp.log
  level: debug

# list of HTTP methods to deny
method_deny:
  - POST
  - DELETE

# list of URL to filter
url_deny:
  basic:
    - statsweb.proxad.net
    - www.searchstarters.com
    - googleads
    - xiti.com
    - googlesyndication
    - scorecardresearch
    - criteo
    - statsweb.proxad.net
    - adscores
    - simpli.fi
    - tubemogul
    - adserver.
    - deployads.com
    - skimresources
    - crosspixel-shopping
    - tradepub.com
    - crsspxl
    - clickiocdn
    - sekundo
    - ads=
    - doubleclick
    - fqtag
    - taboola
    - adnxs
    - c.coll1onf.com
    - adomik
    - gstatic.com
    - spamanalyst
    - teads.tv
    - mathtag.com
    - adsrvr.
    - turn.com
    - openx.
    - 1rx.io
    - 2mdn.net
    - 2o7.net
    - 33across.com
    - 3lift.com
    - a5224106a28855abbbb0825aa5e4cd9bd.profile.ams50.cloudfront.net
    - adadvisor.net
    - adap.tv
    - adblade.com
    - adbrn.com
    - addthis.com
    - addthisedge.com
    - adformdsp.net
    - adform.net
    - adgrx.com
    - adition.com
    - adkernel.com
    - adlucent.com
    - adnxs.com
    - adobedtm.com
    - adrolays.de
    - adroll.com
    - adrtx.net
    - adsafeprotected.com
    - adsrvr.org
    - ad-stir.com
    - ads-twitter.com
    - adsymptotic.com
    - adtech.de
    - adtechus.com
    - advertising.com
    - adx1.com
    - afy11.net
    - agkn.com
    - ajax.googleapis.com
    - akamaihd.net
    - alcmpn.com
    - alexa-top-500-news
    - amazon-adsystem.com
    - amazonaws.com
    - amgdgt.com
    - appier.net
    - apxlv.com
    - areyouahuman.com
    - atdmt.com
    - atsfi.de
    - atwola.com
    - baidu.com
    - bannerflow.com
    - bdex.com
    - betrad.com
    - bf-ad.net
    - bidr.io
    - bidswitch.net
    - bildstatic.de
    - bing.com
    - bizographics.com
    - bizrate.com
    - bkrtx.com
    - bluecava.com
    - bluekai.com
    - bnmla.com
    - bootstrapcdn.com
    - brightcove.com
    - brightcove.net
    - btrll.com
    - bttrack.com
    - budgetedbauer.com
    - c1exchange.com
    - cardlytics.com
    - casalemedia.com
    - chango.com
    - chartbeat.com
    - chartbeat.net
    - choicestream.com
    - circularhub.com
    - clickagy.com
    - cloudflare.com
    - clrstm.com
    - cnevids.com
    - cnzz.com
    - cogocast.net
    - collective-media.net
    - company-target.com
    - comscore.com
    - condenastdigital.com
    - connexity.net
    - contextweb.com
    - conversionlogic.net
    - crazyegg.com
    - creditcards.com
    - crispadvertising.com
    - crisppremium.com
    - criteo.com
    - criteo.net
    - crsspxl.com
    - crwdcntrl.net
    - crypto-js.googlecode.com
    - ctnsnet.com
    - cxense.com
    - d26t7ex48mr4bn.cloudfront.net
    - d31qbv1cthcecs.cloudfront.net
    - d37sfqor0g25ph.cloudfront.net
    - d3qxwzhswv93jk.cloudfront.net
    - d5nxst8fruw4z.cloudfront.net
    - d8rk54i4mohrb.cloudfront.net
    - demdex.net
    - dff7tx5c2qbxc.cloudfront.net
    - df-srv.de
    - disqus.com
    - dmtry.com
    - dnkzzz1hlto79.cloudfront.net
    - dnn506yrbagrg.cloudfront.net
    - domdex.com
    - do-not-tracker.org
    - dotomi.com
    - doubleclick.net
    - dp8hsntg6do36.cloudfront.net
    - dpclk.com
    - dwgyu36up6iuz.cloudfront.net
    - dy48bnzanqw0v.cloudfront.net
    - emetriq.de
    - ensighten.com
    - everesttech.net
    - eviltracker.net
    - exelator.com
    - exoclick.com
    - eyeota.net
    - eyereturn.com
    - eyeviewads.com
    - facebook.com
    - facebook.net
    - fallingfalcon.com
    - fbcdn.net
    - flashtalking.com
    - flite.com
    - fonts.googleapis.com
    - fonts.net
    - fqtag.com
    - fwmrm.net
    - gannett-cdn.com
    - gemius.pl
    - gigya.com
    - googleadservices.com
    - google-analytics.com
    - googlesyndication.com
    - googletagmanager.com
    - googletagservices.com
    - gssprt.jp
    - gstatic.com
    - gtrk.s3.amazonaws.com
    - gumgum.com
    - gwallet.com
    - hlserve.com
    - hotjar.com
    - hrnorth.se
    - iab.net
    - ib-ibi.com
    - imasdk.googleapis.com
    - imrworldwide.com
    - imshopping.com
    - indexww.com
    - insightexpressai.com
    - instinctiveads.com
    - interstateanalytics.com
    - ioam.de
    - ipowow.com
    - ipredictive.com
    - ixiaa.com
    - jivox.com
    - jquery.com
    - jsonip.com
    - jsrdn.com
    - jumptap.com
    - ketchuponnews.com
    - kixer.com
    - komoona.com
    - krxd.net
    - licdn.com
    - lifestreet.com
    - lijit.com
    - linkedin.com
    - liverail.com
    - llnwd.net
    - load.s3.amazonaws.com
    - lrcdn.net
    - mail.ru
    - mathtag.com
    - mdotm.com
    - media6degrees.com
    - media.net
    - mediavoice.com
    - mediawallahscript.com
    - mentad.com
    - mixpanel.com
    - ml314.com
    - moatads.com
    - mookie1.com
    - msn.com
    - mxptint.net
    - myvisualiq.net
    - nativeads.com
    - netmng.com
    - netseer.com
    - newrelic.com
    - newsinc.com
    - nexac.com
    - nr-data.net
    - ntv.io
    - nuggad.net
    - omtrdc.net
    - opendsp.com
    - openx.net
    - optimahub.com
    - optimizely.com
    - outbrain.com
    - owneriq.net
    - parsely.com
    - peer39.com
    - perfectmarket.com
    - petametrics.com
    - pingdom.net
    - pinterest.com
    - pippio.com
    - polarmobile.com
    - postrelease.com
    - powerlinks.com
    - ppjol.net
    - prfct.co
    - pricegrabber.com
    - pro-market.net
    - pubmatic.com
    - quantcount.com
    - quantserve.com
    - raasnet.com
    - reson8.com
    - revcontent.com
    - revsci.net
    - rfihub.com
    - rfihub.net
    - rlcdn.com
    - rqtrk.eu
    - ru4.com
    - rubiconproject.com
    - rundsp.com
    - rutarget.ru
    - rvty.net
    - s3.amazonaws.com
    - sail-horizon.com
    - sascdn.com
    - sbal4kp.com
    - scanscout.com
    - scorecardresearch.com
    - securedvisit.com
    - servedbyopenx.com
    - serving-sys.com
    - sharethis.com
    - sharethrough.com
    - simplereach.com
    - simpli.fi
    - sitescout.com
    - skimresources.com
    - smaato.net
    - smartadserver.com
    - smartclip.net
    - sndcdn.com
    - sonobi.com
    - soundcloud.com
    - spongecell.com
    - spotad.co
    - spotxcdn.com
    - spotxchange.com
    - sprinkletxt.com
    - staticworld.net
    - sundaysky.com
    - survata.com
    - swoop.com
    - taboola.com
    - tailsweep.com
    - tapad.com
    - tealiumiq.com
    - techhive.com
    - tekblue.net
    - theadex.com
    - thebrighttag.com
    - tidaltv.com
    - tiqcdn.com
    - townnews.com
    - trackersimulator.org
    - tracking.
    - travelaudience.com
    - tribalfusion.com
    - truoptik.com
    - tubemogul.com
    - turn.com
    - twimg.com
    - twitter.com
    - typekit.com
    - typekit.net
    - undertone.com
    - univide.com
    - uts-af.com
    - videoamp.com
    - videohub.tv
    - vindicosuite.com
    - visiblemeasures.com
    - visualdna.com
    - visualrevenue.com
    - visualwebsiteoptimizer.com
    - vk.com
    - vmweb.net
    - volvelle.tech
    - w55c.net
    - weborama.
    - wishabi.
    - workey.se
    - wp.com
    - wtp101.com
    - xg4ken.com
    - xplosion.de
    - yadro.ru
    - yahoo.com
    - yandex.ru
    - yieldify.com
    - yieldlab.net
    - yieldmanager.com
    - yieldmanager.net
    - yieldmo.com
    - yieldoptimizer.com
    - yieldpartners.com
    - yimg.com
    - yldbt.com
    - ytimg.com
    - yume.com
    - zemanta.com
    - zergnet.com
    - zqtk.net
    - f7ds.
  
  fancy:
    - symc[bd].com
    - /adserver/i
    - ^ads\.
    - \-ads\.

# list of content-types to filter out
content_types:
    - image/xxxx
